name: DungeonsXLQuests
version: 2.0
description: Quests module for DungeonsXL
author: PikaMug
website: https://github.com/PikaMug/DungeonsXLQuestsModule

main: me.pikamug.dungeonsxlquests
depend: [DungeonsXL, Quests]