name: DungeonsXLQuests
version: 1.3
description: Quests module for DungeonsXL
author: PikaMug
website: https://www.spigotmc.org/resources/dungeonsxl-quests-module.66703/

main: me.pikamug.DungeonsXLQuests
depend: [DungeonsXL, Quests]